notifications:
  email: false

env:
  matrix:
    - ANDROID_TARGET=android-25 
    - ANDROID_ABI=armeabi-v7a
    - ANDROID_TAG=google_apis
    - tools

language: android
jdk:
  - oraclejdk8
android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.3
    - android-25
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-addon-google_apis-google-25
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
 - chmod +x gradlew

before_script:
    - echo no | android create avd --force -n test -t "android-25" --abi $ANDROID_ABI --tag $ANDROID_TAG
    - emulator -avd test -no-skin -no-audio -no-window &
    - android-wait-for-emulator
    - adb shell input keyevent 82 &

script:
 - ./gradlew clean assemble connectedAndroidTest coveralls
