language: android
jdk:
  - oraclejdk8
android:
  components:
    - platform-tools
    - tools

    - build-tools-24.0.2

    - android-24

    - extra-google-m2repository
    - extra-android-m2repository

before_install:
 - chmod +x gradlew

script:
 - ./gradlew clean assemble test
